### ISSUE TITLE
 dmlreadexception in PostgreSQL

### ISSUE THREAD

**Issue by ewallah** [ronefel/moodle-mod_googlemeet#2]
After creating a new instance, I get a database error: relation does not exist. 
Only a (working) button for entering the room is created, then the debugging shows this output:

```
More information about this error

×Debug info: ERROR: relation "mdl_googlemeet_events" does not exist
LINE 2: FROM mdl_googlemeet_events
^
SELECT id,eventdate,duration
FROM mdl_googlemeet_events
WHERE googlemeetid = 1
AND (eventdate > 16070288838828 OR eventdate = 160798272910)
LIMIT 5
[array (
)]
Error code: dmlreadexception
×Stack trace:
line 486 of /lib/dml/moodle_database.php: dml_read_exception thrown
line 329 of /lib/dml/pgsql_native_moodle_database.php: call to moodle_database->query_end()
line 920 of /lib/dml/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->query_end()
line 465 of /mod/googlemeet/locallib.php: call to pgsql_native_moodle_database->get_records_sql()
line 82 of /mod/googlemeet/view.php: call to googlemeet_get_upcoming_events()


```

**Comment by ronefel** [comment]
@ewallah, which database are you using?

**Comment by ronefel** [comment]
Hi @ewallah

Did you have version 0.1.0 and updated to 1.0.0?

If so, please uninstall the plugin and directly install version 1.0.0.

**Comment by mudrd8mz** [comment]
I just ran into this as well. This is because there is hard-coded "mdl_" prefix in the SQL query in `googlemeet_get_upcoming_events()` that reads

```
 FROM mdl_googlemeet_events
```

It must be

```
FROM {googlemeet_events}
```

**Comment by mudrd8mz** [comment]
Reference: https://docs.moodle.org/dev/Data_manipulation_API#Table_prefix

**Comment by ewallah** [comment]
Indeed, David, the error disappears when the hard-coded prefix is removded.

No, Rone, this was a new installation (version 1.0.0).

**Comment by ronefel** [comment]
Thanks @mudrd8mz and @ewallah 

I really was not paying attention it. It is now corrected.
